# Generated by Django 4.2.15 on 2024-08-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_detect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceimage',
            name='url',
            field=models.URLField(default=None),
        ),
    ]
