# Generated by Django 4.2.15 on 2024-08-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_detect', '0002_faceimage_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceimage',
            name='image',
        ),
    ]
