# Generated by Django 4.2.15 on 2024-08-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_detect', '0003_remove_faceimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceimage',
            name='image',
            field=models.FileField(default=None, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
