# Generated by Django 4.2.15 on 2024-08-29 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2024, 8, 29, 11, 37, 57, 24348, tzinfo=datetime.timezone.utc)),
        ),
    ]
