# Generated by Django 4.2.15 on 2024-09-02 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2024, 9, 2, 10, 53, 27, 362226, tzinfo=datetime.timezone.utc)),
        ),
    ]
