# Generated by Django 4.2.16 on 2024-09-17 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_todo_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(default=datetime.date(2024, 9, 17)),
        ),
    ]
