# Generated by Django 4.2.16 on 2024-09-23 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_alter_appuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(default=datetime.date(2024, 9, 23)),
        ),
    ]
