# Generated by Django 4.2.16 on 2024-09-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_alter_appuser_email_alter_appuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
